<a href="https://colab.research.google.com/github/kkarenCevallos/INTELIGENCIA-ARTIFICIAL/blob/main/p2karen_de_Introducci%C3%B3n_Python_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importe numpy como np y vea cual es la versión que esta utilizando

import numpy as np
print(np.__version__)

1.25.2


In [ ]:
#CEVALLOS BRAVO KAREN MISHELLE
#13/07/2024
#INTELIGENCIA ARTIFICIAL

In [ ]:
# Crear una matriz 1D de números del 0 al 9

array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Cree un vector aleatorio de tamaño 10 y reemplace el valor máximo por 0
vector = np.random.rand(10)
print(vector)

print("\nValor maximo cambiado a cero")
maximo = np.argmax(vector)
vector[maximo] = 0
print(vector)

[0.02979579 0.76476325 0.14887706 0.87233556 0.34582956 0.9858201
 0.3642116  0.96195039 0.80690707 0.77257036]

Valor maximo cambiado a cero
[0.02979579 0.76476325 0.14887706 0.87233556 0.34582956 0.
 0.3642116  0.96195039 0.80690707 0.77257036]


In [ ]:
# Imprima el número 8 de la siguiente matriz:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, 2])

8


In [ ]:
# Imprima los números [3, 4, 5] de la siguiente matriz:
arr = np.array([1,2,3,4,5,6,7])
print(arr[2:5])

[3 4 5]


In [ ]:
# Imprima los últimos 4 números de la siguiente matriz:
arr = np.array([1,2,3,4,5,6,7])
print(arr[-4:])

[4 5 6 7]


In [ ]:
# Cree una matriz numpy 3×3 de todos los True
array = np.full((3, 3), True, dtype=bool)
print(array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# Extraer todos los números impares de la funcion arr
odd_numbs = arr[arr % 2 != 0]
print(odd_numbs)

[1 3 5 7]


In [ ]:
# Crea un vector con valores comprendidos entre 10 y 49
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Invertir un vector (el primer elemento se convierte en el último)
vector = np.array([1, 2, 3, 4, 5])
vector_inver = vector[::-1]
print(vector_inver)

[5 4 3 2 1]


In [ ]:
#Cree una matriz de 10x10 con valores enteros aleatorios y encuentre los valores mínimo y máximo
matriz = np.random.randint(0, 51, size=(10, 10))

valor_minimo = np.min(matriz)
valor_maximo = np.max(matriz)

print("Matriz:")
print(matriz)
print("\nValor mínimo:", valor_minimo)
print("Valor máximo:", valor_maximo)

Matriz:
[[22  7 40  8  5 45 21  3 35 14]
 [14 49 19 48 32 17  0 25  4  6]
 [ 9 22 23  2 16 15 47 32 49  6]
 [45  9 35 14 31 48 26 50 48  1]
 [13  7 38 43 50 35 15 38 39 26]
 [49 21 11 14 43 34 24 48 23 10]
 [40 17 23 24  1 27  6 50  7 40]
 [19  6 10 32 24 41 24  3 42 13]
 [ 6 43 44 12 26 49  2 31 25 36]
 [ 2 39 16 13  4 47 43 39 12 12]]

Valor mínimo: 0
Valor máximo: 50


In [ ]:
# Crear una matriz de 3x3x3 con valores aleatorios
array_3dd = np.random.random((3, 3, 3))
print(array_3dd)

[[[0.59236806 0.47918652 0.61805261]
  [0.68165808 0.5118003  0.07792294]
  [0.60097469 0.63315595 0.97838703]]

 [[0.09201449 0.2722641  0.1143961 ]
  [0.42822681 0.71495327 0.09444946]
  [0.63931281 0.02195736 0.81014639]]

 [[0.67531873 0.15496793 0.59216453]
  [0.45788253 0.60588739 0.27253956]
  [0.12547519 0.57800415 0.33226823]]]


In [ ]:
# Reemplace todos los números impares en arr con -1
arr[arr % 2 != 0] = -1
print(arr)

[-1  2 -1  4 -1  6 -1]


In [ ]:
# Creación de una matriz de tipo float
arr_flt = np.array([1.5, 2.3, 3.1, 4.7, 5.5], dtype=float)

print(arr_flt)
print(arr_flt.dtype)

[1.5 2.3 3.1 4.7 5.5]
float64


In [ ]:
# Convertir una matriz 1D en una matriz 2D con 2 filas
arr_1d = np.array([1, 2, 3, 4, 5, 6])

arr_2d = arr_1d.reshape(2, -1)

print("Array 1D:")
print(arr_1d)
print("\nArray 2D con 2 filas:")
print(arr_2d)

Array 1D:
[1 2 3 4 5 6]

Array 2D con 2 filas:
[[1 2 3]
 [4 5 6]]


In [ ]:
# ¿Cómo encontrar valores comunes entre dos matrices?

m1 = np.random.randint(0,10,10)
m2 = np.random.randint(0,10,10)

valores_comunes = np.intersect1d(Z1, Z2)

print("m1:", Z1)
print("m2:", Z2)
print("Valores comunes:", valores_comunes)

m1: [0 0 6 0 3 9 9 9 3 1]
m2: [6 0 3 1 8 7 9 8 0 3]
Valores comunes: [0 1 3 6 9]


In [ ]:
#  Considere dos matrices aleatorias A y B, verifique si son iguales

mA = np.random.randint(0,2,5)
mB = np.random.randint(0,2,5)

comparacion = np.array_equal(mA, mB)

print("mA:", A)
print("mB:", B)
print("\n¿Son iguales?:", comparacion)

mA: [1 0 1 0 0]
mB: [1 1 0 0 1]

¿Son iguales?: False


In [ ]:
# Apilar las matrices a y b verticalmente
vA = np.vstack((A))
vB = np.vstack((B))

apilado_v = np.array([[vA],[vB]])
print(apilado_v)

[[[[1]
   [0]
   [1]
   [0]
   [0]]]


 [[[1]
   [1]
   [0]
   [0]
   [1]]]]


In [ ]:
# Apile las matrices a y b horizontalmente.
hA = np.hstack((A))
hB = np.hstack((B))

apilado_h = np.array([[hA],[hB]])
print(apilado_h)

[[[1 0 1 0 0]]

 [[1 1 0 0 1]]]


In [ ]:
# Obtenga todos los elementos entre 5 y 10 de la matriz tmp.

tmp = np.arange(15)
resultado = tmp[(tmp >= 5) & (tmp <= 10)]

print(tmp)
print("\nElementos entre 5 y 10:", resultado)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Elementos entre 5 y 10: [ 5  6  7  8  9 10]


In [ ]:
# ¿Cómo hacer que una función de python que maneja escalares funcione en matrices numpy?
# Salida deseada:
# A = np.array([5, 7, 9, 8, 6, 4, 5])
# B = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6., 7., 9., 8., 9., 7., 5.])

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

# Vectorizamos la función maxx
pair_max = np.vectorize(maxx)

A = np.array([5, 7, 9, 8, 6, 4, 5])
B = np.array([6, 3, 4, 8, 9, 7, 1])

resultado = pair_max(A, B)

print("Array A:", A)
print("Array B:", B)
print("\nResultado:", resultado)

Array A: [5 7 9 8 6 4 5]
Array B: [6 3 4 8 9 7 1]

Resultado: [6 7 9 8 9 7 5]


In [ ]:
# Intercambie las columnas 1 y 2 en la matriz arr.

arr = np.arange(9).reshape(3,3)
print(arr)

# intercanbiadas columnas 1 y 2


arr[:, [1, 2]] = arr[:, [2, 1]]

print("\nColumna 1 y 2 intercambiadas:")
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

Columna 1 y 2 intercambiadas:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [ ]:
# Crea una matriz 2D de forma 5x3 para contener números decimales aleatorios entre 5 y 10.
# La salida deseada debe ser como la siguiente:


#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]


array2 = np.random.uniform(5, 10, size=(5, 3))

print(array2)

[[9.25318414 7.71276228 7.10042972]
 [5.78935013 7.06906275 5.7358448 ]
 [9.46843575 5.39986686 8.19854411]
 [9.63422574 5.80831202 7.34058552]
 [6.10147232 7.19240506 5.75528878]]
